---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uxethegx/public_html/
    - /bin/cp index.html cv.html projects.html .htaccess $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH