---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uxethegx/public_html/
    - /bin/cp index.html cv.html projects.html .htaccess $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/css $DEPLOYPATH/images $DEPLOYPATH/assets $DEPLOYPATH/api
    - /bin/cp -R css/. $DEPLOYPATH/css/
    - /bin/cp -R images/. $DEPLOYPATH/images/
    - /bin/cp -R assets/. $DEPLOYPATH/assets/
    - /bin/cp -R api/. $DEPLOYPATH/api/
    - /bin/mkdir -p $DEPLOYPATH/videos
    - /bin/cp -R videos/. $DEPLOYPATH/videos/